# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

# https://github.com/actions/labeler
root:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - '*'

docs:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - docs/**/*
              - docs-overrides/**/*
              - README.md

github-actions:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - .github/**/*

licenses:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - licenses/**/*

sedona-common:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - common/**/*

sedona-docker:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - docker/**/*

sedona-flink:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - flink/**/*
              - flink-shaded/**/*

sedona-python:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - python/**/*

sedona-r:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - R/**/*

sedona-snowflake:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - snowflake/**/*
              - snowflake-tester/**/*

sedona-spark:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - spark/**/*
              - spark-shaded/**/*

sedona-zeppelin:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - zeppelin/**/*
