/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package org.apache.sedona.core.spatialPartitioning.quadtree;

import java.io.Serializable;
import java.util.*;
import org.apache.sedona.common.utils.HalfOpenRectangle;
import org.apache.sedona.core.spatialPartitioning.PartitioningUtils;
import org.apache.sedona.core.spatialPartitioning.QuadTreeRTPartitioning;
import org.locationtech.jts.geom.Envelope;
import org.locationtech.jts.geom.Geometry;
import org.locationtech.jts.geom.Point;
import org.locationtech.jts.index.strtree.STRtree;
import scala.Tuple2;

/**
 * The ExtendedQuadTree class uses a modified quad-tree approach for partitioning spatial data, as
 * described in "Simba: Efficient In-Memory Spatial Analytics".
 *
 * <p>In this approach, a global R-tree index is constructed by taking a set of random samples from
 * the dataset and building the R-tree on the master node. For each partition, the distance from the
 * furthest point in the partition to its centroid is calculated. Using the R-tree, the k-nearest
 * neighbors of each centroid are found, and a distance bound is derived for each partition. This
 * bound ensures that the k-nearest neighbors of any point in a partition can be found within a
 * subset of the data identified by a circle range query centered at the centroid with the derived
 * radius. This method guarantees efficient and accurate k-nearest neighbor joins by leveraging both
 * local and global spatial indexing.
 */
public class ExtendedQuadTree<T> extends PartitioningUtils implements Serializable {
  // hold the samples temporarily
  private final transient List<Envelope> samples = new ArrayList<>();

  private final Envelope boundary;
  private final int numPartitions;

  // original partitioning quad tree
  // for non-overlapped partitioning, the original quad tree is used
  private StandardQuadTree<Integer> partitionTree;

  // The expanded boundaries are generated by the quad tree + r-tree
  // for overlapped partitioning, the expanded boundaries are used
  private HashMap<Integer, List<Envelope>> expandedBoundaries;

  // The spatial index for partitioned MBRs
  // for overlapped partitioning, the spatial index is used
  private STRtree spatialExpandedBoundaryIndex;

  private boolean useNonOverlapped = false;
  private boolean useFullGeometry = false;
  private boolean useAccurateKnnPartitioning = false;

  public HashMap<Integer, List<Envelope>> getExpandedBoundaries() {
    return expandedBoundaries;
  }

  public STRtree getSpatialExpandedBoundaryIndex() {
    return spatialExpandedBoundaryIndex;
  }

  /**
   * Constructor to initialize the partitions list.
   *
   * @param boundary
   * @param numPartitions
   */
  public ExtendedQuadTree(Envelope boundary, int numPartitions) {
    this.boundary = boundary;
    this.numPartitions = numPartitions;
  }

  /**
   * Constructor to initialize the partitions list with non-overlapped boundaries.
   *
   * @param extendedQuadTree
   * @param useNonOverlapped
   */
  public ExtendedQuadTree(ExtendedQuadTree<?> extendedQuadTree, boolean useNonOverlapped) {
    this(extendedQuadTree, useNonOverlapped, false);
  }

  /**
   * Constructor to initialize the partitions list with non-overlapped boundaries.
   *
   * @param extendedQuadTree source tree
   * @param useNonOverlapped whether original non-overlapped boundaries are used
   * @param useFullGeometry whether a geometry is routed to every base cell it intersects
   */
  public ExtendedQuadTree(
      ExtendedQuadTree<?> extendedQuadTree, boolean useNonOverlapped, boolean useFullGeometry) {
    this.boundary = extendedQuadTree.boundary;
    this.numPartitions = extendedQuadTree.numPartitions;
    this.expandedBoundaries = extendedQuadTree.expandedBoundaries;
    this.spatialExpandedBoundaryIndex = extendedQuadTree.spatialExpandedBoundaryIndex;
    this.partitionTree = extendedQuadTree.partitionTree;
    this.useNonOverlapped = useNonOverlapped;
    this.useFullGeometry = useFullGeometry;
    this.useAccurateKnnPartitioning = extendedQuadTree.useAccurateKnnPartitioning;
  }

  /**
   * Returns the boundary of the partition zones.
   *
   * @return
   */
  public Envelope getBoundary() {
    return boundary;
  }

  /**
   * Returns the number of partitions.
   *
   * @return
   */
  public int getPartitionNum() {
    return numPartitions;
  }

  /**
   * Insert a new sample into the sample list.
   *
   * @param sample Envelope object to be inserted.
   */
  public void insert(Envelope sample) {
    samples.add(sample);
  }

  /**
   * Check the geometry against the partition zones to find the IDs of overlapping ranges. Note that
   * the geometry can be in multiple ranges because ranges can overlap.
   *
   * @param geometry Geometry object to be placed.
   * @return Iterator of Tuple2 containing partition ID and the corresponding geometry.
   */
  @Override
  public Iterator<Tuple2<Integer, Geometry>> placeObject(Geometry geometry) {
    if (useNonOverlapped) {
      Objects.requireNonNull(geometry, "spatialObject");

      if (useFullGeometry && !(geometry instanceof Point)) {
        return placeFullGeometry(geometry);
      }

      // KNN join uses geometry's centroid to calculate the distance
      final Envelope envelope = geometry.getCentroid().getEnvelopeInternal();

      final List<QuadRectangle> matchedPartitions =
          this.partitionTree.findZones(new QuadRectangle(envelope));

      final Point point = geometry.getCentroid();

      final Set<Tuple2<Integer, Geometry>> result = new HashSet<>();
      for (QuadRectangle rectangle : matchedPartitions) {
        // Ignore null or empty point
        if (point == null || point.isEmpty()) break;

        // For points, make sure to return only one partition
        if (!(new HalfOpenRectangle(rectangle.getEnvelope())).contains(point)) {
          continue;
        }

        result.add(new Tuple2(rectangle.partitionId, geometry));
      }

      // knn join uses the centroid of the geometry
      return result.iterator();
    } else {
      // use the expanded boundaries
      List<Tuple2<Integer, Geometry>> result = new ArrayList<>();
      Envelope objectEnvelope = geometry.getEnvelopeInternal();

      // Query the spatial index for intersecting envelopes
      Collection<Integer> intersectingIds = spatialExpandedBoundaryIndex.query(objectEnvelope);
      if (useAccurateKnnPartitioning) {
        intersectingIds = new LinkedHashSet<>(intersectingIds);
      }

      for (Integer partitionId : intersectingIds) {
        result.add(new Tuple2<>(partitionId, geometry));
      }

      return result.iterator();
    }
  }

  /**
   * Routes a non-point query to each original quadtree cell that the geometry intersects.
   *
   * <p>The local KNN candidates from these cells are merged globally by query row identity. Using
   * exact geometry/cell intersection avoids replicating a sparse line to every cell in its
   * envelope. If a topology predicate cannot be evaluated, envelope routing is used as a safe
   * fallback.
   */
  private Iterator<Tuple2<Integer, Geometry>> placeFullGeometry(Geometry geometry) {
    final Set<Integer> partitionIds = getFullGeometryPartitionIds(geometry);
    final List<Tuple2<Integer, Geometry>> result = new ArrayList<>(partitionIds.size());
    for (Integer partitionId : partitionIds) {
      result.add(new Tuple2<>(partitionId, geometry));
    }
    return result.iterator();
  }

  private Set<Integer> getFullGeometryPartitionIds(Geometry geometry) {
    final List<QuadRectangle> matchedPartitions =
        this.partitionTree.findZones(new QuadRectangle(geometry.getEnvelopeInternal()));
    final Set<Integer> result = new LinkedHashSet<>();

    try {
      for (QuadRectangle rectangle : matchedPartitions) {
        Geometry cell = geometry.getFactory().toGeometry(rectangle.getEnvelope());
        if (geometry.intersects(cell)) {
          result.add(rectangle.partitionId);
        }
      }
    } catch (RuntimeException e) {
      result.clear();
      for (QuadRectangle rectangle : matchedPartitions) {
        result.add(rectangle.partitionId);
      }
    }

    // A non-empty geometry inside the global boundary should intersect at least one cell. Retain
    // envelope matches if numerical precision at a cell edge produces no exact match.
    if (result.isEmpty()) {
      for (QuadRectangle rectangle : matchedPartitions) {
        result.add(rectangle.partitionId);
      }
    }
    return result;
  }

  /**
   * Check the geometry against the partition zones to find the IDs of overlapping ranges. Only
   * returns the IDs of the overlapping partitions. Note that the geometry can be in multiple ranges
   * because ranges can overlap.
   *
   * @param geometry Geometry object to be checked.
   * @return Set of integers representing the IDs of the overlapping partitions.
   */
  @Override
  public Set<Integer> getKeys(Geometry geometry) {
    if (useAccurateKnnPartitioning && useNonOverlapped) {
      Objects.requireNonNull(geometry, "spatialObject");
      if (useFullGeometry && !(geometry instanceof Point)) {
        return getFullGeometryPartitionIds(geometry);
      }

      // knn join uses the centroid of the geometry
      return partitionTree.getKeys(geometry.getCentroid());
    } else if (useAccurateKnnPartitioning) {
      // use the expanded boundaries
      Set<Integer> keys = new HashSet<>();
      Envelope objectEnvelope = geometry.getEnvelopeInternal();

      // Query the spatial index for intersecting envelopes
      List<Integer> intersectingIds = spatialExpandedBoundaryIndex.query(objectEnvelope);

      keys.addAll(intersectingIds);

      return keys;
    } else if (!useNonOverlapped) {
      // Preserve the historical routing exposed by getKeys for legacy KNN partitioners.
      return partitionTree.getKeys(geometry.getCentroid());
    } else {
      Set<Integer> keys = new HashSet<>();
      keys.addAll(spatialExpandedBoundaryIndex.query(geometry.getEnvelopeInternal()));
      return keys;
    }
  }

  @Override
  public List<Envelope> fetchLeafZones() {
    return partitionTree.fetchLeafZones();
  }

  /**
   * Builds the quad-tree partitioning structure and calculates the expanded boundaries for
   * efficient spatial partitioning.
   *
   * <p>This method performs the following steps: 1. Forces the quad-tree to grow to a minimum level
   * to ensure a sufficient number of partitions, which might slightly differ from the specified
   * number. 2. Constructs the quad-tree partitioning using the given samples and boundary,
   * initializing it to the calculated minimum level. 3. Creates the expanded boundaries by building
   * an STR (Sort-Tile-Recursive) tree using the provided number of neighbor samples and sampling
   * probability. 4. Clears the samples to avoid broadcasting them to all nodes involved in
   * partitioning.
   *
   * @param neighborSampleNumber the number of neighbor samples to consider for building the STR
   *     tree.
   */
  public void build(int neighborSampleNumber) throws Exception {
    build(neighborSampleNumber, false);
  }

  /**
   * Builds the partitioning tree and optionally counts identical sample envelopes once when
   * deriving KNN distance bounds.
   *
   * @param neighborSampleNumber the number of neighbour samples
   * @param deduplicateKnnSamples whether identical sample envelopes count once
   */
  public void build(int neighborSampleNumber, boolean deduplicateKnnSamples) throws Exception {
    build(neighborSampleNumber, deduplicateKnnSamples, deduplicateKnnSamples, false);
  }

  /**
   * Builds the partitioner and controls sample-driven KNN distance bounds independently from sample
   * deduplication.
   *
   * @param neighborSampleNumber the number of neighbour samples
   * @param deduplicateKnnSamples whether identical sample envelopes count once
   * @param useKnnSamples whether samples are used and insufficient samples trigger a safe fallback
   */
  public void build(int neighborSampleNumber, boolean deduplicateKnnSamples, boolean useKnnSamples)
      throws Exception {
    build(neighborSampleNumber, deduplicateKnnSamples, useKnnSamples, useKnnSamples);
  }

  /**
   * Builds the partitioner and independently gates the new accurate planar placement behavior.
   *
   * @param neighborSampleNumber the number of neighbour samples
   * @param deduplicateKnnSamples whether identical sample envelopes count once
   * @param useKnnSamples whether samples are used and insufficient samples trigger a safe fallback
   * @param useAccurateKnnPartitioning whether to use exact bounds and replica-safe placement
   */
  public void build(
      int neighborSampleNumber,
      boolean deduplicateKnnSamples,
      boolean useKnnSamples,
      boolean useAccurateKnnPartitioning)
      throws Exception {
    // Force the quad-tree to grow up to a certain level
    // So the actual num of partitions might be slightly different
    int minLevel = (int) Math.max(Math.log(numPartitions) / Math.log(4), 0);
    QuadTreeRTPartitioning quadTreeRTPartitioning =
        new QuadTreeRTPartitioning(samples, boundary, numPartitions, minLevel);
    partitionTree = quadTreeRTPartitioning.getPartitionTree();

    // Create the expanded boundaries
    quadTreeRTPartitioning.buildSTRTree(
        samples,
        neighborSampleNumber,
        deduplicateKnnSamples,
        useKnnSamples,
        useAccurateKnnPartitioning);
    expandedBoundaries = quadTreeRTPartitioning.getMbrs();
    spatialExpandedBoundaryIndex = quadTreeRTPartitioning.getMbrSpatialIndex();
    this.useAccurateKnnPartitioning = useAccurateKnnPartitioning;

    // Make sure not to broadcast all the samples used to build the Quad
    // tree to all nodes which are doing partitioning
    samples.clear();
    partitionTree.dropElements();
  }

  public StandardQuadTree<?> getQuadTree() {
    return partitionTree;
  }
}
