authors:
  kelly:
    name: Kelly-Ann Dolor
    description: Staff Technical Writer, Apache Sedona
    avatar: https://static.licdn.com/aero-v1/sc/h/9c8pery4andzj6ohjkjp54ma2
  matt_powers:
    name: Matthew Powers
    description: Staff Developer Relations Engineer, Apache Sedona
    avatar: https://media.licdn.com/dms/image/v2/C4E03AQHL3oztZlTr2w/profile-displayphoto-shrink_200_200/profile-displayphoto-shrink_200_200/0/1517751981945?e=2147483647&v=beta&t=66hsE-PF25_Uc1EbjnljUOmqjl3NwJ0lHAcZkusxnO0