<<<<<<< HEAD
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

=======
>>>>>>> 97cd25dc74 ([DOCS] adding blog post, fixing blog post formatting, adding blog options)
authors:
  kelly:
    name: Kelly-Ann Dolor
    description: Staff Technical Writer, Apache Sedona
<<<<<<< HEAD
    avatar: https://media.licdn.com/dms/image/v2/C4D03AQHKr_fPpGdNGw/profile-displayphoto-shrink_400_400/profile-displayphoto-shrink_400_400/0/1516866211726?e=2147483647&v=beta&t=p4PcyFNjZhvAIX8e1qZt4i3HbH5yOIXuEs8MTNoYZ3Y
  matt_powers:
    name: Matthew Powers
    description: Staff Developer Relations Engineer, Apache Sedona
    avatar: https://media.licdn.com/dms/image/v2/C4E03AQHL3oztZlTr2w/profile-displayphoto-shrink_200_200/profile-displayphoto-shrink_200_200/0/1517751981945?e=2147483647&v=beta&t=66hsE-PF25_Uc1EbjnljUOmqjl3NwJ0lHAcZkusxnO0
  matt_forrest:
    name: Matthew Forrest
    description: Director of Customer Engineering & Product Led Growth, Wherobots
    avatar: https://media.licdn.com/dms/image/v2/D4E03AQHxYTrEgc53_g/profile-displayphoto-shrink_200_200/profile-displayphoto-shrink_200_200/0/1722352936567?e=2147483647&v=beta&t=X10Z02O2UX8IRmbypcw-m-jbIDeNsPWWL-YOPX_v1XQ
=======
    avatar: https://static.licdn.com/aero-v1/sc/h/9c8pery4andzj6ohjkjp54ma2
  matt_powers:
    name: Matthew Powers
    description: Staff Developer Relations Engineer, Apache Sedona
    avatar: https://media.licdn.com/dms/image/v2/C4E03AQHL3oztZlTr2w/profile-displayphoto-shrink_200_200/profile-displayphoto-shrink_200_200/0/1517751981945?e=2147483647&v=beta&t=66hsE-PF25_Uc1EbjnljUOmqjl3NwJ0lHAcZkusxnO0
>>>>>>> 97cd25dc74 ([DOCS] adding blog post, fixing blog post formatting, adding blog options)
