# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

rules:
  unpinned-uses:
    config:
      policies:
        actions/*: any
        astral-sh/setup-uv: any
        docker/setup-qemu-action: any
        github/*: any
        pypa/cibuildwheel: any
        pypa/gh-action-pypi-publish: any
        r-lib/actions/check-r-package: any
        r-lib/actions/setup-r: any
        r-lib/actions/setup-r-dependencies: any
